#!/usr/bin/env bash
# install nginx and set /redirect me

sudo apt-get update
sudo apt-get install -y nginx

# allowing nginx on port 80
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

my_server_setup="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	location / {
		try_files \$uri \$uri/ =404;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}"

echo -e "$my_setup" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
