#!/usr/bin/env bash
#read from /etc/passwd
while IFS=: read -r username password user_id group_id user_info home_dir default_shell
do
	echo "The user $username is part of the $group_id gang, lives in the $home_dir and rides $default_shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
